version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    command: python3 app.py
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db